/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lucia
 */
public class TelaPrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalVIEW
     */
    public TelaPrincipalVIEW() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsair = new javax.swing.JButton();
        btnDadosPessoais = new javax.swing.JButton();
        lblfundocinza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsair.setBackground(new java.awt.Color(255, 255, 255));
        btnsair.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        btnsair.setForeground(new java.awt.Color(51, 51, 51));
        btnsair.setText("Sair");
        btnsair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsairMouseExited(evt);
            }
        });
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, 30));

        btnDadosPessoais.setBackground(new java.awt.Color(255, 255, 255));
        btnDadosPessoais.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        btnDadosPessoais.setForeground(new java.awt.Color(51, 51, 51));
        btnDadosPessoais.setText("Dados Pessoais");
        btnDadosPessoais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDadosPessoais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDadosPessoaisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDadosPessoaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDadosPessoaisMouseExited(evt);
            }
        });
        btnDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosPessoaisActionPerformed(evt);
            }
        });
        getContentPane().add(btnDadosPessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        lblfundocinza.setForeground(new java.awt.Color(51, 51, 51));
        lblfundocinza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Cinza.jpg"))); // NOI18N
        getContentPane().add(lblfundocinza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 278));

        setSize(new java.awt.Dimension(434, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDadosPessoaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDadosPessoaisMouseEntered
        // TODO add your handling code here:
        btnDadosPessoais.setBackground(new Color(51, 51, 51));
        btnDadosPessoais.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnDadosPessoaisMouseEntered

    private void btnDadosPessoaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDadosPessoaisMouseExited
        // TODO add your handling code here:
        btnDadosPessoais.setBackground(new Color(255, 255, 255));
        btnDadosPessoais.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnDadosPessoaisMouseExited

    private void btnDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosPessoaisActionPerformed
        // TODO add your handling code here:
        DadosPessoaisVIEW telaDados = null;
        telaDados = new DadosPessoaisVIEW();
        telaDados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDadosPessoaisActionPerformed

    private void btnDadosPessoaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDadosPessoaisMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_btnDadosPessoaisMouseClicked

    private void btnsairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsairMouseEntered
        // TODO add your handling code here:
         btnsair.setBackground(new Color(51, 51, 51));
        btnsair.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnsairMouseEntered

    private void btnsairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsairMouseExited
        // TODO add your handling code here:
        btnsair.setBackground(new Color(255, 255, 255));
        btnsair.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnsairMouseExited

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        // TODO add your handling code here:
       
        this.dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDadosPessoais;
    private javax.swing.JButton btnsair;
    private javax.swing.JLabel lblfundocinza;
    // End of variables declaration//GEN-END:variables
}
