package view;

import controller.CadastroController;
import Jm.JMascara;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import javax.swing.JFormattedTextField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

public class CadastroView extends javax.swing.JFrame {
    MaskFormatter data;
    private final CadastroController controller;

    public CadastroView() {
         try {
            data = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(CadastroView.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
  
        //INSTANCIA O CONTROLADOR NA PROPRIA VIEW
        controller = new CadastroController(this);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        btnGtipoAgente = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnGsexo = new javax.swing.ButtonGroup();
        btnsair = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        btnindividual = new javax.swing.JRadioButton();
        btncoletivo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnmasculino = new javax.swing.JRadioButton();
        btnfeminino = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        txtareacultural = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescricao = new javax.swing.JEditorPane();
        jLabel17 = new javax.swing.JLabel();
        btncadastrar = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JTextField();
        txtdata = new javax.swing.JFormattedTextField(data);
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jScrollPane1.setViewportView(jEditorPane1);

        jLabel19.setText("jLabel19");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnsair.setBackground(new java.awt.Color(51, 51, 51));
        btnsair.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        btnsair.setForeground(new java.awt.Color(255, 255, 255));
        btnsair.setText("Sair");
        btnsair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsairMouseExited(evt);
            }
        });
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair);
        btnsair.setBounds(10, 480, 70, 22);

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CADASTRO");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(160, 10, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Cinza.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 55);

        txtcpf.setForeground(new java.awt.Color(51, 51, 51));
        txtcpf.setSelectionColor(new java.awt.Color(51, 51, 51));
        txtcpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcpfKeyReleased(evt);
            }
        });
        getContentPane().add(txtcpf);
        txtcpf.setBounds(70, 70, 150, 30);

        txtnome.setForeground(new java.awt.Color(51, 51, 51));
        txtnome.setSelectionColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtnome);
        txtnome.setBounds(190, 110, 260, 30);

        btnGtipoAgente.add(btnindividual);
        btnindividual.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        btnindividual.setForeground(new java.awt.Color(51, 51, 51));
        btnindividual.setText("Individual");
        btnindividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnindividualActionPerformed(evt);
            }
        });
        getContentPane().add(btnindividual);
        btnindividual.setBounds(330, 160, 80, 20);

        btnGtipoAgente.add(btncoletivo);
        btncoletivo.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        btncoletivo.setForeground(new java.awt.Color(51, 51, 51));
        btncoletivo.setText("Coletivo");
        btncoletivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoletivoActionPerformed(evt);
            }
        });
        getContentPane().add(btncoletivo);
        btncoletivo.setBounds(420, 160, 80, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tipo De Agente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 160, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Cpf/Cnpj:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 70, 60, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nome Completo / Razão Social:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 200, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 220, 50, 20);

        btnmasculino.setBackground(new java.awt.Color(255, 255, 255));
        btnGsexo.add(btnmasculino);
        btnmasculino.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        btnmasculino.setForeground(new java.awt.Color(51, 51, 51));
        btnmasculino.setText("Masculino");
        btnmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasculinoActionPerformed(evt);
            }
        });
        getContentPane().add(btnmasculino);
        btnmasculino.setBounds(350, 220, 80, 20);

        btnfeminino.setBackground(new java.awt.Color(255, 255, 255));
        btnGsexo.add(btnfeminino);
        btnfeminino.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        btnfeminino.setForeground(new java.awt.Color(51, 51, 51));
        btnfeminino.setText("Feminino");
        getContentPane().add(btnfeminino);
        btnfeminino.setBounds(430, 220, 80, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Área Cultural:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 220, 100, 30);

        txtareacultural.setForeground(new java.awt.Color(51, 51, 51));
        txtareacultural.setSelectionColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtareacultural);
        txtareacultural.setBounds(100, 220, 190, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Descrição:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 310, 110, 20);

        txtdescricao.setSelectionColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(txtdescricao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 270, 410, 140);

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Data Nascimento:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 160, 120, 30);

        btncadastrar.setBackground(new java.awt.Color(51, 51, 51));
        btncadastrar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        btncadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btncadastrar.setText("Cadastrar");
        btncadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncadastrarMouseExited(evt);
            }
        });
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastrar);
        btncadastrar.setBounds(200, 430, 130, 50);

        btnvoltar.setBackground(new java.awt.Color(51, 51, 51));
        btnvoltar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        btnvoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnvoltar.setText("Voltar");
        btnvoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnvoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnvoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnvoltarMouseExited(evt);
            }
        });
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltar);
        btnvoltar.setBounds(430, 480, 70, 22);

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Senha:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(280, 70, 50, 30);

        txtsenha.setForeground(new java.awt.Color(51, 51, 51));
        txtsenha.setSelectionColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtsenha);
        txtsenha.setBounds(330, 70, 140, 30);

        txtdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdataActionPerformed(evt);
            }
        });
        getContentPane().add(txtdata);
        txtdata.setBounds(110, 160, 90, 30);

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Branco Top.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 50, 370, 470);

        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Branco Top.jpg"))); // NOI18N
        jLabel18.setText("jLabel2");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 50, 480, 470);

        setSize(new java.awt.Dimension(526, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
        LoginView telaLogin = null;
        try {
            telaLogin = new LoginView();
            telaLogin.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        try {
            //CHAMA O MÉTODO DO CONTROLADOR  CadastroController
            controller.cadastrar();
            this.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CadastroView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnindividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnindividualActionPerformed


    }//GEN-LAST:event_btnindividualActionPerformed

    private void btncoletivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoletivoActionPerformed

    }//GEN-LAST:event_btncoletivoActionPerformed

    private void btnmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasculinoActionPerformed

    }//GEN-LAST:event_btnmasculinoActionPerformed

    private void btncadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncadastrarMouseEntered
        // TODO add your handling code here:
        btncadastrar.setBackground(new Color(153, 153, 153));
        btncadastrar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btncadastrarMouseEntered

    private void btncadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncadastrarMouseExited
        // TODO add your handling code here:
        btncadastrar.setBackground(new Color(51, 51, 51));
        btncadastrar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btncadastrarMouseExited

    private void btnvoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvoltarMouseEntered
        // TODO add your handling code here:
        btnvoltar.setBackground(new Color(153, 153, 153));
        btnvoltar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnvoltarMouseEntered

    private void btnvoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvoltarMouseExited
        // TODO add your handling code here:
        btnvoltar.setBackground(new Color(51, 51, 51));
        btnvoltar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnvoltarMouseExited

    private void txtcpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcpfKeyReleased
        // TODO add your handling code here:
        txtcpf.setText(JMascara.GetJmascaraCpfCnpj(txtcpf.getText()));
    }//GEN-LAST:event_txtcpfKeyReleased

    private void txtdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataActionPerformed

    private void btnsairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsairMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsairMouseEntered

    private void btnsairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsairMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsairMouseExited

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroView().setVisible(true);
        });
    }

    public JTextField getTxtareacultural() {
        return txtareacultural;
    }

    public JTextField getTxtcpf() {
        return txtcpf;
    }

    public JFormattedTextField getTxtdata() {
        return txtdata;
    }

    public JEditorPane getTxtdescricao() {
        return txtdescricao;
    }

    public JTextField getTxtnome() {
        return txtnome;
    }

    public JTextField getTxtsenha() {
        return txtsenha;
    }

    public JRadioButton getBtncoletivo() {
        return btncoletivo;
    }

    public JRadioButton getBtnfeminino() {
        return btnfeminino;
    }

    public JRadioButton getBtnindividual() {
        return btnindividual;
    }

    public JRadioButton getBtnmasculino() {
        return btnmasculino;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGsexo;
    private javax.swing.ButtonGroup btnGtipoAgente;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JRadioButton btncoletivo;
    private javax.swing.JRadioButton btnfeminino;
    private javax.swing.JRadioButton btnindividual;
    private javax.swing.JRadioButton btnmasculino;
    private javax.swing.JButton btnsair;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtareacultural;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JEditorPane txtdescricao;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsenha;
    // End of variables declaration//GEN-END:variables

}
